config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'main_pages#index', as: 'root'
  resources :management
  resources :options
  resources :main_pages
  resources :sources do
    resources :articles
  end
  delete 'delete_all_articles', to: 'articles#delete_all', as: 'delete_all_articles'
  get 'parse', to: 'main_pages#parse', as: 'parse'
  get 'reset', to: 'main_pages#reset', as: 'reset'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :source
  validates :headline, uniqueness: true
  scope :date_uniq, -> { group('created_at::date').count.keys.sort }
end

app/models/option.rb
# frozen_string_literal: true

class Option < ApplicationRecord
  enum agents: ['Linux Firefox', 'Linux Mozilla', 'Mac Mozilla', 'Windows IE 6', 'Windows IE 9', 'Windows Mozilla',
                'iPad']
end

app/models/source.rb
class Source < ApplicationRecord
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def create
    @article = Article.create(article_params)
    if @article.save
      flash[:success] = 'Article added.'
    else
      flash[:error] = @source.errors.full_messages
      @article.errors.full_messages
    end
  end

  def article_params
    params.require(:article).permit(:link, :headline, :snippet, :date)
  end

  def delete_all
    Article.all.each(&:destroy)
    redirect_to root_path
  end

end

app/controllers/main_pages_controller.rb
# frozen_string_literal: true
class MainPagesController < ApplicationController

  def index
    parameters = params.permit(params.keys).to_h.map { |e, _i| e.to_i }.select(&:positive?)
    cookies[:filter_sources] = parameters
    @articles = Article.all
    @articles = @articles.where('created_at::date = ?', params[:date]) if params[:date].present?
    @articles = @articles.where({ source_id: parameters }) if parameters.size.positive?
    @pagy, @articles = pagy(@articles, items: 10)
    @articles = sort @articles
    respond_to do |format|
      format.js
      format.html
    end
  end

  def test_form
    @articles = Article.all
  end

  def reset
    redirect_to '/'
  end

  def parse
    parse_nytimes if params[:NYT].present?
    parse_wsj if params[:WSJ].present?
    parse_bloomberg if params[:Bloomberg].present?
    parse_economist if params[:The_Economist].present?
    redirect_to '/'
  end

  def parse_economist
    init_mechanize
    page = @agent.get('https://www.economist.com/search?q=ukraine&sort=date')
    page.css('a._search-result').each do |link|
     s = (link.css('span._headline').text).split('|')[0]
     s2 = link.css('img._image')[0]['src']
     s3 = s2
     @article = Article.create(link: link[:href], headline: s, snippet: link.css('p._snippet').text.split('...')[1],
                               date: Time.now, source_id: Source.find_by(name: 'The_Economist').id, image: s3)
     @article.save
   end
  end

  def parse_nytimes
    init_mechanize
    page = @agent.get('https://www.nytimes.com/search?dropmab=false&query=ukraine&sort=newest')
    page.css('div.css-1kl114x').each do |link|
      p parse_link = "https://www.nytimes.com#{link.css('.css-e1lvw9 a')[0]['href']}"
      image_link = link.css('.css-rq4mmj[src]')
      image_link = image_link.map { |element| element['src'] }.join
      @article = Article.create(link: parse_link, headline: link.css('p').text, snippet: link.css('h4').text,
                                date: Time.now, source_id: Source.find_by(name: 'NYT').id, image: image_link)
      @article.save
    end
  end

  def parse_bloomberg
    init_mechanize
    page = @agent.get('https://www.bloomberg.com/search?query=Ukraine#')
    page.css('.storyItem__4d5aa17d67').each do |link|
      p '777'
      p link.css('a.headline__96ba1917df').text
      parse_link = link.css('a.headline__96ba1917df')[0]['href']
      p link.css('a.summary__f7259c7b77').text
      unless link.css('img.thumbnail__55f7ac7947').to_s == ''
        image_link = link.css('img.thumbnail__55f7ac7947')[0]['src']
      end
      image_link = '' if link.css('img.thumbnail__55f7ac7947').to_s == ''
      @article = Article.create(link: parse_link, headline: link.css('a.headline__96ba1917df').text,
                                snippet: link.css('a.summary__f7259c7b77').text, date: Time.now,
                                source_id: Source.find_by(name: 'Bloomberg').id, image: image_link)
      @article.save
      p '__________________________________________'
    end
  end

  def parse_wsj
    init_mechanize
    page = @agent.get('https://www.wsj.com/search?query=Ukraine')
    page.search('div.WSJTheme--search-result--2NFlrTX7').each do |link|
      p '777'
      p link.search('span.WSJTheme--headlineText--He1ANr9C').text
      # parse_link = link.search('a.WSJTheme--headline--unZqjb45 undefined WSJTheme--heading-3--2z_phq5h typography--serif-display--ZXeuhS5E')[0]['href']
      p link.css('span.WSJTheme--summaryText--2LRaCWgJ').text
      unless link.css('img.WSJTheme--lazy-load').to_s == ''
        p image_link = link.css('img.WSJTheme--lazy-load-wrapper--1TOawUTd ')[0]['src']
      end
      image_link = '' if link.css('img.WSJTheme--lazy-load-wrapper--1TOawUTd').to_s == ''
      # @article = Article.create(link: parse_link, headline: link.css('a.headline__96ba1917df').text,
      #                           snippet: link.css('a.summary__f7259c7b77').text, date: Time.now, source_id: Source.find_by(name: 'Bloomberg').id, image: image_link)
      # @article.save
      p '__________________________________________'
    end
  end

  def show; end

  def article_params
    params.require(:article).permit(:link, :headline, :snippet, :date, :image)
  end

  def sort(articles)
    if params[:sort_option] == 'ASC'
      articles.order(created_at: :ASC)
    else
      articles.order(created_at: :desc)
    end
  end
end

def init_mechanize
  @agent = Mechanize.new
  @agent.user_agent_alias = Option.first.agent
end

app/controllers/management_controller.rb
class ManagementController < ApplicationController
  def index; end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :set_option, only: %i[update]
  def index
    @option = Option.first
  end

  def update
    respond_to do |format|
      if @option.update(option_params)
        format.html { redirect_to options_path, notice: 'Options was successfully updated.' }
        format.json { render :index, status: :ok, location: @option }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render options_path: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  def option_params
    params.require(:option).permit(:agent)
  end

  def set_option
    @option = Option.find(params[:id])
  end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_action :set_source, only: %i[edit update ]

  def index
    @sources = Source.all
    @source = Source.new
  end

  def new; end

  def edit; end

  def create
    @source = Source.create(source_params)
    if @source.save
      flash[:success] = 'Source added.'
      redirect_to sources_path
    else
      flash[:error] = @source.errors.full_messages
      @source.errors.full_messages
      render 'index'
    end
  end

  def update
    respond_to do |format|
      if @source.update(source_params)
        format.html { redirect_to sources_path, notice: 'Source was successfully updated.' }
        format.json { render :index, status: :ok, location: @source }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  def set_source
    @source = Source.find(params[:id])
  end

  def source_params
    params.require(:source).permit(:name, :description, :country, :language)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/main_pages_helper.rb
module MainPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <head>
    <title>Parser7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom_style", media: 'all', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
  </head>

  <body>
  <div class="container">
    <%= render 'shared/navbar' %>
    <%= yield %>
  </div>
  </body>

app/views/main_pages/_filter.html.erb
<div >
  <%= form_with(url: root_path, method: :get, remote: true)  do |form| %>
    <% Source.all.each do |source|  %>
      <div class="form-check form-check-inline">
        <%= form.check_box source.id, include_hidden: false, id: "filter_#{source.name}_hj", checked:  cookies[:filter_sources].include?(source.id), onchange: "this.form.submit();", class: "form-check-input" %>
        <%= form.label source.name, class: "form-check-label"  %>
      </div>
    <% end %>
    <%= select_tag(:date, options_for_select(Article.date_uniq, params[:date]), prompt: "All", class: "btn btn-outline-primary float-end my_button_bootstrap btn-sm", onchange: "this.form.submit();") %>
    <%= select_tag(:sort_option, options_for_select([["Sort by Date High to Low","DESK"], ["Sort by Date Low to High","ASC"]], params[:sort_option]), class:"btn btn-outline-primary float-end my_button_bootstrap btn-sm", onchange: "this.form.submit();") %>
    <%= link_to 'Reset filters', reset_path, class:"btn btn-outline-primary my_button float-end btn-sm" %>
  <% end %>
</div>

app/views/main_pages/_form.html.erb
<div class="border-top my-2"></div>

<small>
  <div class="row bg-light text-dark">
    <div class="col-2  d-none d-md-block">
      <h6> Image </h6>
    </div>
    <div class="col-3  d-none d-md-block">
      <h6> Headline </h6>
    </div>
    <div class="col-4 d-none d-md-block">
      <h6> Snippet </h6>
    </div>
    <div class="col-1 d-none d-md-block">
      <h6> link </h6>
    </div>
    <div class="col-1 d-none d-md-block">
      <h6> Date </h6>
    </div>
    <div class="col-1 d-none d-md-block">
      <h6> Source </h6>
    </div>
  </div>
  <div class="border-top my-2"></div>


  <% @articles.each do |article| %>
    <div class="row table-hover">
      <div class="col-md-2 border-right">
        <%= image_tag article.image, alt: "Picture should be here", width: "180px", height: "80%" %>
      </div>
      <div class="col-sm-3 col-md-3 border-left fw-bold">
        <%= article.headline %>
      </div>
      <div class="col-md-4 border-right">
        <%= article.snippet %>
      </div>
      <div class="col-md-1 border-right">
        <a href="<%= article.link %>" , target="_blank">link to source</a>
      </div>
      <div class="col-md-1 border-right">
        <%= article.date.strftime('%F') %>
      </div>
      <div class="col-md-1 border-right">
        <%= article.source.name %>
      </div>
    </div>
    <div class="border-top my-2"></div>
  <% end %>

  <%== pagy_bootstrap_nav(@pagy) %>
</small>

app/views/main_pages/index.html.erb
<div class="container random-number">
  <% if @articles.nil? %>
    <h5> Articles exist </h5>>
  <% else %>
    <%= link_to 'Add filters', root_path(:filter_marker => 'yes'), class: "btn btn-outline-primary me-2 btn-sm" if params[:filter_marker] != 'yes' %>
    <% if params[:filter_marker] == 'yes' %>
      <%= link_to 'Hide filters', root_path, class: "btn btn-outline-primary me-2 btn-sm" if params[:filter_marker] == 'yes' %>
      <%= render 'filter' %>
    <% end %>
    <%= render 'form', articles: @articles %>
  <% end %>
</div>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>


<button type="button" onclick="Rails.ajax({url: 'main_pages/test_form', type: 'get'})" style="padding: 6px">
  test_form
</button>

<div class="random-book"></div>

app/views/main_pages/test_form.js.erb
$('.random-number').html("<%= j (render partial: 'form') %>")

app/views/management/_form.html.erb
<small>

  <div class="row bg-primary">
    <div class="col-2">
      <h4> Image </h4>
    </div>
    <div class="col-3">
      <h4> headline </h4>
    </div>
    <div class="col-4">
      <h4> snippet </h4>
    </div>
    <div class="col-1">
      <h4> link </h4>
    </div>
    <div class="col-1">
      <h4> Date </h4>
    </div>
    <div class="col-1">
      <h4> Source </h4>
    </div>
  </div>
  <div class="border-top my-2"></div>


  <% articles.each do |article| %>
      <div class="col-md-1 border-right">
        <%= article %>
      </div>
    </div>
    <div class="border-top my-2"></div>
  <% end %>
</small>

app/views/management/index.html.erb
<div class="container">
<div class="d-grid gap-2">
  <%= link_to 'sources', sources_path, class: "btn btn-outline-primary me-2" %>
  <%= link_to 'parse', parse_path, class: "btn btn-outline-primary me-2" %>
  <%= button_to 'Delete all from articles',  delete_all_articles_path, method: :delete, data: { confirm:  'Are you sure?' }, class: "btn btn-outline-primary me-2" %>

  <%= form_with(url: parse_path, method: :get) do |form| %>
    <% Source.all.each do |source|  %>
      <div class="form-check form-check-inline">
      <%= form.check_box source.name, include_hidden: false %>
      <%= form.label source.name  %>
      </div>
    <% end %>
    <div class="d-grid gap-2">
      <button class="btn btn-outline-primary me-2" type="submit">parse select</button>
    </div>
  <% end %>
</div>
</div>
<%= Article.date_uniq.class %>

<%= '_________________' %>


  <%= render 'form', articles: Article.date_uniq %>

<h1>Welcome, this is the home page</h1>

<button type="button"
        class="btn btn-lg btn-danger"
        data-bs-toggle="popover"
        title="Popover title"
        data-bs-content="Amazing content, right ?">
  Click to toggle popover
</button>

app/views/options/_form.erb
<%= form_with(model: option) do |form| %>
  <% if option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(option.errors.count, "error") %> prohibited this option from being saved:</h2>
      <ul>
        <% option.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <%= form.label :agent %>
    <div class="col-md-4">
      <%= form.select( :agent, options_for_select(Option.agents.map{ |key, value| [key.capitalize, value]}, option.agent),{}, { :class => 'btn btn-outline-primary btn-sm' }) %>
    </div>

  </div>

   <div class="actions">
    <%= form.submit class: "btn btn-outline-primary btn-sm" %>
  </div>
<% end %>

app/views/options/index.html.erb
<%= render 'form', option: @option %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href=management>Management</a>
        <li class="nav-item">
           <a class="nav-link" href=options>Options</a>
        </li>
       </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/sources/_form.html.erb
<%= form_with(model: source) do |form| %>
  <% if source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(source.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% source.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-control">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control form-control-lg" %>
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control form-control-lg" %>
    <%= form.label :country %>
    <%= form.text_field :country, class: "form-control form-control-lg" %>
    <%= form.label :language %>
    <%= form.text_field :language, class: "form-control form-control-lg" %>
    <%= form.submit class: "btn btn-outline-primary me-2" %>
  </div>
<% end %>

app/views/sources/edit.html.erb
<h1> Editing Sources </h1>

<%= render 'form', source: @source %>

<%= link_to 'Back', sources_path %>

app/views/sources/index.html.erb
<div class="row">
  <div class="col-2">
    <h4> Name </h4>
  </div>
  <div class="col-4">
    <h4> Description </h4>
  </div>
  <div class="col-2">
    <h4> Country </h4>
  </div>
  <div class="col-2">
    <h4> Language </h4>
  </div>
</div>

  <% @sources.each do |source| %>
  <div class="row">
    <div class="col-2">
      <%= source.name %>
    </div>
    <div class="col-4">
      <%= source.description %>
    </div>
    <div class="col-2">
      <%= source.country %>
    </div>
    <div class="col-2">
      <%= source.language %>
    </div>
     <div class="col-2">
    <%= link_to 'Edit', edit_source_path(source),  class: "btn btn-outline-primary me-2" %>
    </div>
  </div>
  <% end %>
</p>
  <%= link_to 'Add sources', sources_path(:add_marker => 'yes'), class: "btn btn-outline-primary me-2" %>
  <% if params[:add_marker] == 'yes'%>
    <%= render 'form', source: @source %>
  <% end %>

app/views/sources/new.html.erb
<%= render 'form', source: @source %>